version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
